title       = "jsinfo"
baseURL     = "https://jsinfo-cli.tamnd.com/"
description = "Browse JavaScript.info modern JavaScript tutorial"
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/jsinfo-cli"
